### ISSUE TITLE
Scriptable wait point command-line option CAP32_WAITBREAK

### ISSUE THREAD

**Issue by cpcitor** [ColinPitrat/caprice32#110]
This continues #108.

Wish an autocmd option like `-a CAP32_WAITBREAK` that delays the processing of subsequent autocmd until emulated program performs something ("something" by default can be when CPC reset (technically when Z80 PC=0 but can be other event like RST 6 PC=0x30 or any other value).

Useful:

* for unattended tests (unit tests of caprice32 itself or of some other code running in emulator)
* for situations when the emulator is launched by some other program like an emulator front-end (game kiosk), as a screensaver or who knows what.

**Comment by cpcitor** [comment]
From #108:

> The CAP32_WAITBREAK is indeed quite powerful. It would allow to replace --reset-exits with -a CAP32_WAITBREAK -a CAP32_EXIT and do much more as you suggested. So if you have time & will to implement it, it would be great !

# Success! :smiley: 

I now have an implementation working! :tada: 

`cap32 -a 'mode 1:print"Hello World":call 0' -a CAP32_WAITBREAK -a CAP32_SCRNSHOT -a CAP32_EXIT `

It produces this:

![screenshot_20171230_232921](https://user-images.githubusercontent.com/1204208/34457698-c020c960-edb9-11e7-8632-f75cc704f4ef.png)

# Walkthrough

It's not obvious that the thing captured the only frame where "Hello world" is both completely drawn and not yet removed!
I could have added a `CALL &BD19` in any case before the `call 0`.
I analyzed local execution log and explain below what happens.

The sources of difficulty:

* The current autocmd use a queue of `SDL_Event` (all `SDL_KeyboardEvent`), which means that for each CAP32 command we must assign a SDL event. I guess this was somehow natural when inserting only text, yet some `CAP32*` do not fit well.
* Anyway it was simpler to follow the existing pattern so I chose to assign `CAPR32_WAITBREAK` to `SDL_BREAK`. I don't know if there's a better choice. :question: 
* Current code has a pattern which assigns a SDL key to every `CAP32_*` (e.g. `CAP32_DEBUG`), which includes language-dependent keymaps. I had to follow the same pattern to get the event through. :innocent: 
* We need `z80_execute()` to return and let us know when `CAP32_WAITBREAK` (PC=0 here) is satisfied. 
    * I used the breakpoint feature of Z80 emulator to get that behavior. 
    * But right after that return, code has to disable the breakpoint at this point in time to let emulation continue, else all subsequent calls to `z80_execute()` just return immediately. 
    * Each call to `z80_execute()` may execute up to about 1 frame or ~80000 instructions. It we don't pay attention, a second breakpoint may happen during that time and we would miss it. To avoid that I simply enable the trace feature of the Z80 emulator. Thanks to this, the breakpoint is set again after one Z80 instruction. :relaxed: 
* Then... `CAP32_SCRNSHOT` happened way too late! Too many frames pass between the end of autotyped text and the processing of `CAP32_WAITBREAK` then `CAP32_SCRNSHOT`. The reason is that both are inserted as `KeyUp` then `KeyDown` event with two-frame delay to satisfy firmware debouncer. To avoid this problem, I turned the virtual event insertion "if" into a loop and introduce a delay only if the event is an actual keypress (to preserve debouncing) and since I have access to the field that says if keypress is up or down, I only ensure minimal delay needed by firmware (tested).
* Currently, the spurious `Enter` keypress introduced by `-a` is what cause a one-frame delay which let firmware finish to write "world" letters. Without it, BASIC should have done `call &BD19:call 0` or screenshot would only show `Hello`. :bowtie: 

# Conclusion

It works! I'll cleanup the code and offer a PR.

Cheers!

**Comment by cpcitor** [comment]
I think this issue can be considered closed. What do you think @ColinPitrat ?

**Comment by ColinPitrat** [comment]
I agree, let's close it. We can open a new one if a need arise that is not covered.
Thanks!
