### ISSUE TITLE
Stryker in the Crypts of Trogan - Mode CPC Plus

### ISSUE THREAD

**Issue by CodyMast** [ColinPitrat/caprice32#113]
Hello,
First I would like to thank you for this superb emulators!
In addition, I have a problem with this game "Stryker in the Crypts of Trogan", it is compatible "CPC Plus" with an additional color palette, but when I run this game with the emulator in "Plus" configuration, the game loads in "CPC" mode. Is there a parameter to add in the file "cap32.cfg" so that the "CPC plus" is recognized?

**Comment by ColinPitrat** [comment]
I gave it a try and indeed, even when model is set to 6128+, the game doesn't manage to detect it.
I'll see if I can find out what fails.

**Comment by ColinPitrat** [comment]
I'm now missing the text (score, level, etc)

**Comment by ColinPitrat** [comment]
Should be playable now.
The text is flickering though, so there's still a bug to fix.

**Comment by CodyMast** [comment]
You rock !
The correction despite the flicker, is already very good, thank you!

**Comment by ColinPitrat** [comment]
I'll call it done :-)
