### ISSUE TITLE
Resolution - Double size (Stretch) in Filter Mode

### ISSUE THREAD

**Issue by FloLore** [ColinPitrat/caprice32#115]
Hi ColinPitrat,

Great job for displaying all graphic modes in 32 bpp! But could not we have a stretched picture in full screen mode for 1080p resolution? (With graphic filters such as scale2x or supereagle)
A check option "Stretch" or an automatic implementation for example ...

**Comment by ColinPitrat** [comment]
I'm not sure what you mean. Do you mean stretch both vertically and horizontally on non-4:3 resolutions ? Or do you mean maximize on the most constraining dimension ?

On my laptop where the native resolution is 2560x1040, if I set this resolution in the configuration file (scr_width = 2560, scr_height=1040), then using 'Double size with hardware flip' in fullscreen stretch the display to use the whole height of the screen.

With 'non-hardware flip' drivers, it doesn't. But setting scr_width=768 and scr_height=540 (twice the resolution of the CPC) will do it (it involves a resolution change to a non-native resolution though)

**Comment by FloLore** [comment]
Only the "Double size with hardware flip" mode allows the display to be stretched to resolutions higher than "scr_width = 768 and scr_height = 540". But would it be possible that this stretching can be available with the graphic modes such as "super eagle, scale2x, etc ...): either a 4/3 stretch on 16/9, or a stretching of resolution while preserving the 4/3.

I have a screen with a native resolution 1080p, but the stretch available under the graphics driver "nvidia" does not allow to stretch the resolution 768x540 to 1920x1080...

**Comment by ColinPitrat** [comment]
Is setting scr_width = 768 and scr_height = 540 an issue ? Or 800 and 600 if the previous doesn't work ?

**Comment by FloLore** [comment]
In 800x600, the stretch is good, but in 4/3 and without this being the native resolution of the screen. I wish I could run the emulator in 1920x1080 with stretching and if possible a graphic filter like supereagle ...

**Comment by ColinPitrat** [comment]
OK, I guess if your native resolution is 1920x1080 you could try some modes among 1024×576, 1152×648, 1280×720, 1366×768, 1600×900 that would offer a better stretching.

The two options to get bigger pictures in native resolutions are:
 - use a hardware surface, this would need to refactor the video driver to make it an option orthogonal to the video driver rather than a video driver itself
 - implement video drivers providing 3x and/or 4x scaling (the latter would be great for your case): https://en.wikipedia.org/wiki/Pixel-art_scaling_algorithms

**Comment by ColinPitrat** [comment]
This should be fully solved with SDL2 which I should merge in the master branch any time now.
cf. #185
