### ISSUE TITLE
How to load raw files?

### ISSUE THREAD

**Issue by wiktortomczak** [ColinPitrat/caprice32#116]
Hey,

This project is so cool! Thanks for working on it.

How do I load [Gunfright](https://www.myabandonware.com/game/gunfright-6u5)? It comes as what I suppose is raw files `GUNFRIGH` `GUNFRIG1.BIN` `GUNFRIG2.BIN`, not as `.dsk` disk image or similar.

Not sure if this is related to #4.

**Comment by ColinPitrat** [comment]
Under linux, you can use iDSK to create a `.dsk` and copy files there:
https://github.com/cpcsdk/idsk
I think it also works for windows but they don't provide a release.

**Comment by scautura** [comment]
There's also ManageDsk (which is what I use) for Windows: http://amstrad.eu/modules/publisher/item.php?itemid=179 (find the bold text "téléchargeable ici" for the download)

iDSK is based on the ManageDsk code, but it seems like it hasn't been updated since.

**Comment by wiktortomczak** [comment]
iDSK worked fine, thanks!
