### ISSUE TITLE
Weak Sectors Protection do not work

### ISSUE THREAD

**Issue by FloLore** [ColinPitrat/caprice32#119]
Hi Colin,

Following your resolution on barbarian, I tested games that did not work before, and that still do not work now. As for example: Arkanoid 2, Dragon ninja, Defenders of the earth, Target renegade, Road blasters, Spherical, all in "original - UK retail". These games are protected by the "Weak Sectors", you have details on this site for arkanoid for example "http://www.cpc-power.com/index.php?page=detail&onglet=dumps&num=299" with details : HexaDump "http://www.cpc-power.com/HexaDump.php?fiche=299&slot=10&rang=0", SectorView "http://www.cpc-power.com/SectorView.php?fiche=299&slot=10&rang=0", SectorData" http://www.cpc-power.com/SectorData.php?fiche=299&slot=10&rang=0".

Do you think you can improve the compatibility of the emulator so that this protection can load? If of course the problem comes from there, your wise look will certainly answer :)

Best regards,
FloLore

**Comment by ColinPitrat** [comment]
Interesting, this is described in one short paragraph here:
http://www.cpcwiki.eu/index.php/Format:DSK_disk_image_file_format#Extensions_to_the_above_specification

Where a sector has weak/random data, there are multiple copies stored. The actual sector size field in the SECTOR INFORMATION LIST describes the size of all the copies. To determine if a sector has multiple copies then compare the actual sector size field to the size defined by the N parameter. For multiple copies the actual sector size field will have a value which is a multiple of the size defined by the N parameter. The emulator should then choose which copy of the sector it should return on each read.

In the case you give, Track 0, Side 0, Sector 7 has a size of 512B but there are actually 1536B (i.e 3 copies) stored in the DSK. So I need to keep the information of the number of copy and rotate on them to answer reads.

**Comment by ColinPitrat** [comment]
This should now work.

**Comment by FloLore** [comment]
You're good, that's for sure! :)

**Comment by FloLore** [comment]
Thank you very much for all your work! I will continue to test and keep you informed of any issues (if any) as you go. I am not a programmer, but if I can contribute by testing, because I find your emulator remarkable, still a big thank you !!

Best Regards

FloLore
