### ISSUE TITLE
Unread track data

### ISSUE THREAD

**Issue by FloLore** [ColinPitrat/caprice32#120]
Hi Colin,

I found a problem reading on original games where the information console indicates an unread track data. So it's impossible to run these games. Here are the screenshots of the info for each of these games:

Puffy' Saga : "https://ibb.co/G9Vnx6h"
Boulder Dash : "https://ibb.co/WDPCsF8"
Camelot Warrior : "https://ibb.co/473d5ZQ" -> works on winape
Nonamed : "https://ibb.co/WDPCsF8"

These tracks are recognized as invalid by the emulator, but maybe they are an unrecognized protection? When you have time, if you can take a look :)

Best Regards,

FloLore

**Comment by ColinPitrat** [comment]
Would you have links to the corresponding roms ?

**Comment by ColinPitrat** [comment]
For boulder dash, SectorView reports some tracks (40 & 41) of size 0 which is likely the issue:
http://www.cpc-power.com/SectorView.php?fiche=460&slot=10&rang=0

This is similar for Camelot Warrior.

This is easy to fix.

**Comment by ColinPitrat** [comment]
Fixed the empty tracks issue with:
https://github.com/ColinPitrat/caprice32/commit/47da615f79b6d84333e13718f75aab08a6e7b14e

The screenshot for Nonamed is not the right one and I couldn't find any DSK that doesn't work.

The 'too many sectors' issue remains ...

**Comment by FloLore** [comment]
- With "Boulder Dash" it works very well now.
- For "Puffy's saga", maybe the dump of the floppy is not correct ...
- For "camelot warrior" the problem on the error is solved but the game does not start, can be a problem of dump too?
- For "nonamed" the version is no longer on the site "cpcpower" because the dump was not correct.
-> I think you did the best for this problem because indeed for "puffy's saga" the sector problem is probably related to the dump.

**Comment by ColinPitrat** [comment]
The problem for Camelot Warrior is probably not an issue with the dump itself but with the emulator.
I'll rename the issue and keep it open until I have time to dig a bit more.

**Comment by ColinPitrat** [comment]
Opened #125 for Camelot Warrior.
