### ISSUE TITLE
Add application menu shortcut GNU/Linux

### ISSUE THREAD

**Issue by cpcbegin** [ColinPitrat/caprice32#123]
An Caprice32 menu shortcut will be life more easier to newbies.
I enclose the files I add for myself with all the necessary files in right path (it also creates a new category 'emulators')
[caprice32_linux_link.zip](https://github.com/ColinPitrat/caprice32/files/2718097/caprice32_linux_link.zip)

**Comment by ColinPitrat** [comment]
The proposition is interesting but I'm wondering:
 - what is the licence of the emulator.png ? Maybe we could reuse the disk.bmp instead.
 - how does this mix with the debian package configuration (that is available under the debian directory)
 - how to insert it into the repository ? I'm tempted to simply put it under resources for now, which means distributions / users have to pick it and put it in the right place.

**Comment by sebhz** [comment]
I'll check the impact on debian packaging this week.
BTW I also need to create a debian package for the 4.5.0 release you made a couple of days ago (and possibly add IPF support to debian packaging, at last. I believe the IPF library license allows us to package it, as long as we do not charge anything for it, right ?).

**Comment by cpcbegin** [comment]
The file emulator.png belongs to Juan Carlos Fernández Amestoy the creator of [RetroVirtualMachine](https://www.retrovirtualmachine.org/).
I asked him if he allow us to add this file as icon for a common category for all GNU/Linux emulators and he said yes (and allow modifications).
About how to add these files into the deb if I see something I'll tell you.

**Comment by sebhz** [comment]
I know how to add them - thanks. I just need to find some time to modify the makefile.
Anyway I will need to work on those to add IPF support to Debian. I'll add the proper lines in the install target for Debian. Bare with me for a few more days :-)

**Comment by ColinPitrat** [comment]
This was added a while ago in https://github.com/ColinPitrat/caprice32/commit/d0b3c96746bd3205252064ec6575c081b842592a
