### ISSUE TITLE
Include debian packaging testing in continuous integration

### ISSUE THREAD

**Issue by ColinPitrat** [ColinPitrat/caprice32#128]
As mentionned in PR #127 after merging it, it would be nice to have a validation of debian packaging on Travis.

**Comment by ColinPitrat** [comment]
@sebhz Can you detail what needs to be done to validate that the package creation works ?

**Comment by sebhz** [comment]
You probably need to build on a debian-based system. I am not aware of cross-debian-building on other distros. This might be possible though...

Then it is just a matter of following the procedure in the INSTALL.md file: 

- `sudo apt-get install dpkg-dev pbuilder` # Hopefully this is enough

Then modify debian/changelog file first line to have a known version. Debian packaging system checks that the version of the binary (from the release directory name I believe) matches the one in debian/changelog (BTW... this is currently 20170601-1 and should really be 4.5.0. I'll need to fix this). For CI sanity check, you can extract what is in the current changelog and use it, it does not really matter. Or override the version number 
- Compile with `make VERSION=<version>`
- Go to `release/cap32_linux/caprice32-<version>/debian`
- Execute `debuild -us -uc --lintian-opts --profile debian`

If this does not crash, the .deb file will be located in `release/cap32_linux` (from memory)

**Comment by ColinPitrat** [comment]
OK, the packaging does another build of the package but let's not worry too much about it :-)

Another dependency that is not mentionned in INSTALL.md is `quilt`

**Comment by ColinPitrat** [comment]
Introduced the possibility to build the package with `make deb_pkg VERSION=4.5.0 REVISION=1` in https://github.com/ColinPitrat/caprice32/commit/a76b9d3085d4020ccce2992813a2dd016b0791b8

Validate the package creation on travis with https://github.com/ColinPitrat/caprice32/commit/86e05bf36c4f7e627dff2d6f9d451c35d7cb12d6

**Comment by ColinPitrat** [comment]
We now have a validation of the package creation on travis: https://travis-ci.org/ColinPitrat/caprice32/builds/477763546

This allowed to update the list of required dependency: https://github.com/ColinPitrat/caprice32/commit/5c3e8f0cb8f16d3030cf271bf3eb6c8081f79b15
