### ISSUE TITLE
Cannot compile on Debian 8 Jessie

### ISSUE THREAD

**Issue by bert003** [ColinPitrat/caprice32#13]
Installed SDL2.0.4 from website.
Installed libfreetype6 and zlib
When executing make, I get the following errors... shown in the attached files...

Errors starting to appear as shown below
![error1](https://cloud.githubusercontent.com/assets/20399702/16732274/a98e0ef4-477c-11e6-92d5-7e3c784f0f9e.png)

They continue to appear as above and end up like below
![error2](https://cloud.githubusercontent.com/assets/20399702/16732288/b3c73fd0-477c-11e6-96c4-0caeb0361065.png)

**Comment by ColinPitrat** [comment]
This is because caprice32 still uses SDL 1.2.
You'll need libsdl1.2-dev.

SDL 1.2 and SDL 2 can co-exist on the system.

I keep the issue open because a check should be added to ensure the proper dependencies are found and not try building if it's not the case.

**Comment by ColinPitrat** [comment]
I updated the makefile to add a check of dependencies.

Can you retry building before installing SDL 1.2 to verify this gives you the proper instructions ?

**Comment by ColinPitrat** [comment]
Should be OK. Please re-open if not.

**Comment by bert003** [comment]
Sorry for late reply.

Downloaded ZIP file, install sdl1.2 library and dev files in Debian 8 Jessie and successfully compiled caprice32. Cheers.

Now I would like to share the cap32 file. Please instruct.

When I run the emulator, I get emulator_init() failed. Aborting. I guess since I do not have any ROM right now.

I copied the cap32 executable file in /usr/local/bin.

By default it is looking for cap32.cfg in /etc. Can that be changed please?

Also where does it look for ROM files?

Thanks
