### ISSUE TITLE
permission to port into libretro

### ISSUE THREAD

**Issue by DSkywalk** [ColinPitrat/caprice32#130]
Hello Colin! :+1: 

I am D_Skywalk developer from Pituka/Wiituka (opensource projects created from cap32) and now I'm trying to get a better CPC Emulator on RetroArch:
https://github.com/libretro/libretro-cap32
Check my gunstick code for Wiituka: http://david.dantoine.org/envio/114/
Maybe it can be useful.

I think your ASIC/CPC+ code is great and I would like to ask you for permission to port it in into libretro.
Can I use it? 

Thanks and sorry for my terrible english! :walking_man:

**Comment by ColinPitrat** [comment]
Yes if course, no problem to reuse the code. As far as I can see this is compatible with the GPL v2+ licensing.

**Comment by DSkywalk** [comment]
Thanks a lot, Colin! :dancer:
