### ISSUE TITLE
Linux Snapfile installation for Caprice 4.5.0 is available

### ISSUE THREAD

**Issue by stanmichalski** [ColinPitrat/caprice32#131]
A new SNAP installation for this great Amstrad CPC emulator is now available for Linux at Snap Store :

URL : https://snapcraft.io/caprice32

Caprice32 snap is compatible with all Linux 64 bits distributions/releases (Ubuntu, Debian, Mint, Fedora...) with snapd is installed.

To install Caprice32 4.5.0 release just open a terminal then enter the following commands :
sudo snap install caprice32
snap connect caprice32:joystick
snap info caprice32

To launch Caprice32 :
- from desktop : Applications/Games/Caprice32
- from terminal : caprice32.launcher

**Comment by ColinPitrat** [comment]
Thanks for this contribution. You can fill the licensing information (GPL v2).

I should add this to the README.

**Comment by stanmichalski** [comment]
Done. Just add the licensing information into Snap store page.

Regards.

**Comment by ColinPitrat** [comment]
Added a word about it in README.md
