### ISSUE TITLE
IDE environment to load/compile/make/debug

### ISSUE THREAD

**Issue by rogergithubbing** [ColinPitrat/caprice32#134]
Hello,

Which could be the best environment to be able to work with, debut, make etc ? Eclipse ? Visual Studio ? Embarcadero ?

Please, Would someone be kind enough to make a mini tutorial of how to start editing and generating the solution , debug it, etc ?

Thanks !

Roger

**Comment by ColinPitrat** [comment]
I personally use vim. But emacs is good too. Any IDE should work fine a long as it's able to run make and handle C++ code ...

Plenty of people already wrote tutorial about how using vim in general and for C++ specifically (and you should be able to find something for any other editor):
https://www.google.com/search?q=vim+tutorial
https://www.google.com/search?q=vim+tutorial+for+c%2B%2B

For building and running caprice32, the only things you need to do are already documented in INSTALL.md:
```
make
./cap32
```

**Comment by rogergithubbing** [comment]
Wow ! thanks for your super quick answer, I'll give vim a try asap.

Regards,

Roger

**Comment by rogergithubbing** [comment]
Hello,

I've been trying to compile it from windows 10: when I try to run "make -n ARCH=win32" in order to create a command file to see which orders will execute, I see that a lot of errors happen; for example:

- To fix some of them, git had to be installed
- the command "mkdir -p " is generated, but windows does not have "-p" option
-  I have to set the variable "TRIPLE" to something different than " x86_64-w64-mingw32"... because it tries to execute the order "i686-w64-mingw32-g++" that does not exists... seems that a lot more of work needs to be done in windows ...

Thanks,

Roger

**Comment by ColinPitrat** [comment]
The build on Windows is done using msys2. You can see more about how it's configured in appveyor.yml. AFAIK, nobody contributes to caprice32 from Windows but you're welcome to try it out and document it. If some modifications needs to be done to the makefile to make it work, they are welcome as long as it remains manageable.

The problem is that if the build is not tested regularly, it's likely to break at one point. So we would also need to setup sone continuous build for it.

**Comment by rogergithubbing** [comment]
Hello,

Thanks for your answer.

Pardon me for being a noob here, but I have some basic questions, and I'd be glad if you can help me going along.

When you say "nobody contributes to caprice32 **FROM** Windows", you mean that nobody uses msys2 to build caprice32 ?

About your advice to setup some continous building for the windows version, I agree with you of course, but as you can see I'm starting to understand how all this works, so I'm not yet ready to even think about it.

But little by little, I think I'm going forward: I've installed msys2 from https://www.msys2.org/ (32 bit version as I'd like to make it compatible with older pcs).
In order to prepare the environment, I've run the following commands inside the msys2 32 bit command prompt: 

to update db: pacman -Sy
to get the compilers and debuggers:

 pacman -S mingw-w64-i686-gcc
 pacman -S mingw-w64-i686-gdb
 
 pacman -S mingw-w64-x86_64-gcc
 pacman -S mingw-w64-x86_64-gdb
 
 Get the git, make cmake and pkg-config tools:
 
 pacman -S git
 pacman -S make
 pacman -S mingw-w64-i686-cmake
 pacman -S mingw-w64-x86_64-cmake
 pacman -S mingw-w64-i686-pkg-config
 pacman -S mingw-w64-x86_64-pkg-config
 
 Get the sources:
 
 git clone https://github.com/ColinPitrat/caprice32
 
The files were obtained successfully, as I was able to view them in the corresponding folder.

Next, I tried to make the project for Windows 

make ARCH=win32

But I got similar message errors:

For every source file *.cpp, I'm getting an error: "/bin/sh: i686-w64-mingw32-g++: command not found"

Finally, I get "make: *** [makefile:137: obj/win32/src/argparse.o] Error 127"

Does "make ARCH=win32" make use of the "appveyor.yml" file ?

I'm on the right track or totally out of path ?

Thanks again,

Roger

**Comment by ColinPitrat** [comment]
> When you say "nobody contributes to caprice32 FROM Windows", you mean that nobody uses msys2 to build caprice32 ?

Yes, that's what I mean. As far as I know, the msys2 build is used only by appveyor for the continuous build of windows packages (available under https://github.com/ColinPitrat/caprice32/releases).

The i686-w64-mingw32-g++ package should be provided by mingw-w64-i686_64-gcc package. In appveryor.yml, the call to make is:

```
make ARCH=win32 MINGW_PATH="/mingw32"
```

The missing MINGW_PATH may be the reason why the command is not found. If it doesn't work, then you have to look for where the g++ command is installed and why make doesn't find it.

Note that you probably want to build in 64 bits, in which case you need only to install the w64-x86_64 packages and you need to give MINGW_PATH="/mingw64".

**Comment by rogergithubbing** [comment]
>Note that you probably want to build in 64 bits

As I said, "(32 bit version as I'd like to make it compatible with older pcs)".

So, in my pc, I'm doing well trying to use 'make' from msys2 ?  No need to use appveyor on my pc ? I don't understand the function of appveyor.yml, I don't know even if I have to use/edit it to be able to build on my pc.

Meanwhile, I'll try the latest recommendations you are giving me in order to build from msys2.

**Comment by ColinPitrat** [comment]
No you don't need appveyor on your PC, appveyor is a service that does a build on each pull request:
https://ci.appveyor.com/project/ColinPitrat/caprice32
and appveyor.yml is the configuration for this service.

**Comment by rogergithubbing** [comment]
Hello,

For my folder structure, it worked with this, without changing the makefile:

make ARCH=win32 MINGW_PATH="."

I finally got it compiled, cap32.exe, after understanding the makefile and copy all the necessary libs and includes. 

But I've got an error at the final line:

i686-w64-mingw32-g++  -o cap32.exe obj/win32/src/argparse.o obj/win32/src/asic.o obj/win32/src/cap32.o obj/win32/src/cartridge.o obj/win32/src/configuration.o obj/win32/src/crtc.o obj/win32/src/disk.o obj/win32/src/fdc.o obj/win32/src/fileutils.o obj/win32/src/glfuncs.o obj/win32/src/gui/src/CapriceAbout.o obj/win32/src/gui/src/CapriceGui.o obj/win32/src/gui/src/CapriceGuiView.o obj/win32/src/gui/src/CapriceLoadSave.o obj/win32/src/gui/src/CapriceMemoryTool.o obj/win32/src/gui/src/CapriceMenu.o obj/win32/src/gui/src/CapriceOptions.o obj/win32/src/gui/src/CapriceRomSlots.o obj/win32/src/gui/src/CapriceVKeyboard.o obj/win32/src/gui/src/CapriceVKeyboardView.o obj/win32/src/gui/src/std_ex.o obj/win32/src/gui/src/wg_application.o obj/win32/src/gui/src/wg_button.o obj/win32/src/gui/src/wg_checkbox.o obj/win32/src/gui/src/wg_color.o obj/win32/src/gui/src/wg_dropdown.o obj/win32/src/gui/src/wg_editbox.o obj/win32/src/gui/src/wg_fontengine.o obj/win32/src/gui/src/wg_frame.o obj/win32/src/gui/src/wg_groupbox.o obj/win32/src/gui/src/wg_label.o obj/win32/src/gui/src/wg_listbox.o obj/win32/src/gui/src/wg_menu.o obj/win32/src/gui/src/wg_message.o obj/win32/src/gui/src/wg_messagebox.o obj/win32/src/gui/src/wg_message_client.o obj/win32/src/gui/src/wg_message_server.o obj/win32/src/gui/src/wg_navigationbar.o obj/win32/src/gui/src/wg_painter.o obj/win32/src/gui/src/wg_picture.o obj/win32/src/gui/src/wg_point.o obj/win32/src/gui/src/wg_progress.o obj/win32/src/gui/src/wg_radiobutton.o obj/win32/src/gui/src/wg_rect.o obj/win32/src/gui/src/wg_renderedstring.o obj/win32/src/gui/src/wg_resources.o obj/win32/src/gui/src/wg_resource_handle.o obj/win32/src/gui/src/wg_scrollbar.o obj/win32/src/gui/src/wg_tab.o obj/win32/src/gui/src/wg_textbox.o obj/win32/src/gui/src/wg_timer.o obj/win32/src/gui/src/wg_toolbar.o obj/win32/src/gui/src/wg_tooltip.o obj/win32/src/gui/src/wg_view.o obj/win32/src/gui/src/wg_window.o obj/win32/src/gui/src/wutil_log.o obj/win32/src/ipf.o obj/win32/src/keyboard.o obj/win32/src/log.o obj/win32/src/psg.o obj/win32/src/savepng.o obj/win32/src/slotshandler.o obj/win32/src/stringutils.o obj/win32/src/tape.o obj/win32/src/video.o obj/win32/src/z80.o obj/win32/src/zip.o obj/win32/main.o ./lib/libSDL.dll.a ./lib/libfreetype.dll.a ./lib/libz.dll.a ./lib/libpng16.dll.a ./lib/libpng.dll.a
mkdir -p release/cap32-win32
rm -f release/cap32-win32.zip
cp cap32.exe release/cap32-win32/
[ -f ./bin/SDL.dll ] && cp ./bin/SDL.dll release/cap32-win32/; [ -f ./bin/libbz2-1.dll ] && cp ./bin/libbz2-1.dll release/cap32-win32/; [ -f ./bin/libfreetype-6.dll ] && cp ./bin/libfreetype-6.dll release/cap32-win32/; [ -f ./bin/libpng16-16.dll ] && cp ./bin/libpng16-16.dll release/cap32-win32/; [ -f ./bin/libstdc++-6.dll ] && cp ./bin/libstdc++-6.dll release/cap32-win32/; [ -f ./bin/libwinpthread-1.dll ] && cp ./bin/libwinpthread-1.dll release/cap32-win32/; [ -f ./bin/zlib1.dll ] && cp ./bin/zlib1.dll release/cap32-win32/; [ -f ./bin/libglib-2.0-0.dll ] && cp ./bin/libglib-2.0-0.dll release/cap32-win32/; [ -f ./bin/libgraphite2.dll ] && cp ./bin/libgraphite2.dll release/cap32-win32/; [ -f ./bin/libharfbuzz-0.dll ] && cp ./bin/libharfbuzz-0.dll release/cap32-win32/; [ -f ./bin/libiconv-2.dll ] && cp ./bin/libiconv-2.dll release/cap32-win32/; [ -f ./bin/libintl-8.dll ] && cp ./bin/libintl-8.dll release/cap32-win32/; [ -f ./bin/libpcre-1.dll ] && cp ./bin/libpcre-1.dll release/cap32-win32/;
**make: *** [makefile:180: distrib] Error 1**

the cap32.exe has been generated, but when I try to launch it, it complains about not finding those dlls:

libfreetype-6.dll
libpng16-16.dll
SDL.dll
libwinpthread-1.dll

I assume that they had not been generated as long as the make process failed at the end, but it does not give me details about the reason. How can I continue ?

Thanks in advance,

Roger

**Comment by ColinPitrat** [comment]
These libraries are not generated, they are provided by the packages listed in appveyor.yml that you may have not installed (you didn't list them in your previous comment).
