### ISSUE TITLE
new green monitor formula at libretro core

### ISSUE THREAD

**Issue by DSkywalk** [ColinPitrat/caprice32#135]
Hello Colin!

To achieve a correct green monitor emulation on CPC+ I created a formula to convert RGB colors to green-luma. Please check this issue, maybe it could be useful to you :+1: 

https://github.com/libretro/libretro-cap32/issues/49

![imagen](https://user-images.githubusercontent.com/560310/54270483-cdf41780-457f-11e9-9353-94e43ce36607.png)

Any improvement, is welcomed too ;)

Thanks! :dancer:

**Comment by zackizacki** [comment]
The rick dangerous screenshot shows IMHO a good advantage. Is my assumption correct, that an implementation would not cost any additional CPU performance, since just another look up table is used?

**Comment by ColinPitrat** [comment]
Yes, you're right, this would be easy to implement and shouldn't have any performance impact.

**Comment by zackizacki** [comment]
Well, I would give it a try. Maybe it can be made available via a command option at first, and later as 
a second monochrome mode in the gui?
I have a green cpc phosphor screen next to my pc display and I notice that the phosphor has a little bluish touch. Just as the many images the google search shows via "cpc 464 green screen" do seem to have as well.
So the formula would probably not be 0%,100%,0%, but 0%,100%,15%.

**Comment by ColinPitrat** [comment]
I think it would be nice to have a config option for that (not necessarily in the GUI, at least not at first). Then you can have the original one, the libretro one and your blueish version to make comparisons, and we can make either the most similar to real screen pictures or the most readable the default.

**Comment by ColinPitrat** [comment]
Thanks @DSkywalk for suggesting this!
