### ISSUE TITLE
V 4.5 breaks autorun

### ISSUE THREAD

**Issue by nportillo2** [ColinPitrat/caprice32#136]
Have 200 .dsk and ramdomly some of the files stoped loading since v 4.5 with autorun.

Caprice32 writes nonsense like RU2943Bs instead of RUN"1943.BAS and returns syntax error.

Not every disk fails, maybe 40%

It worked flawless on previous version.

**Comment by nportillo2** [comment]
I have more information on this issue. 

Problem is with some remaped games. It happens when I choose "Amstrad Keyboard" for player 1 as option and asign some keys to a joystick button, like "Space" for button B.

I don't press anything on the joystick, but autorun writes nonsense when autorun begins, like "RUb4634". I noticed the command text for autorun is linked with the keys assigned.

**Comment by nportillo2** [comment]
Just moved to Crocods. RMP files are compatible and everything works.

Closed as Caprice32 looks dead.

**Comment by ColinPitrat** [comment]
Caprice32 is not dead. I'll try to reproduce and investigate.

**Comment by ColinPitrat** [comment]
I couldn't reproduce despite trying multiple 1943 DSK. On the other hand, all of them use 'run"1943' not 'run"1943.bas' ...

Do you have the issue with the latest release ?
On windows or linux ? 
Is it systematically on the same .dsk that you encounter the issue ?
Are you capping emulation speed at 100% or not ? If capped, does it reach 100% ?

**Comment by ColinPitrat** [comment]
What do you mean by:
'Problem is with some remaped games. It happens when I choose "Amstrad Keyboard" for player 1 as option and assign some keys to a joystick button, like "Space" for button B.'

Where do you set this ? In the game itself ? If so this happens after the autorun. Or do you modify keymaps yourself ?

**Comment by ColinPitrat** [comment]
Wait, crocods is an amstrad emulator for nintendo DS. Caprice32 doesn't support nintendo DS.
Are you looking for AmeDS ?

**Comment by sebhz** [comment]
@nportillo2 it looks like you did modify the keymap files yourself, right ?
Could you please post the keymap file you are using ?

**Comment by DSkywalk** [comment]
Colin @nportillo2 is using libretro:
https://github.com/libretro/libretro-cap32/issues/62

**Comment by ColinPitrat** [comment]
Thanks for clarifying!
