### ISSUE TITLE
Real Joysticks don't work in Linux Mint

### ISSUE THREAD

**Issue by sprudel79** [ColinPitrat/caprice32#142]
I have an issue using real joysticks (e.g. Speedlink Competition USB or also Xbox360 Controller) with Caprice32 4.5 under Linux Mint 19.3 Cinnemon.
I have disabled Joystick emulation in the menu and enabled Joystick support, however in games where a joystick is supported they don't work. Any hints?
Thanks in advance.

**Comment by sprudel79** [comment]
Ok sorry, I have to correct myself: it works now....
I had installed the SNAP version of caprice32 4.5 from https://snapcraft.io/caprice32 which didn't support any real joysticks. I have just compiled the latest sources directly and now it works like a charm.

**Comment by ColinPitrat** [comment]
Note that from the page you point to:

> To detect joystick in snap strict confinement use command : snap connect caprice32:joystick

Did you try it?

**Comment by sprudel79** [comment]
Thanks @ColinPitrat  for your hint. No, I haven't tried it and didn't know that it exists. But good to know that there's a possibility to deal with the issue. Right now I am happy with the compiled version but I might switch again to the snap version since I don't need to care for any version updates :-)
The only thing I would love to see in future is a possibility to map the fire button similar to the menu button :-)
