### ISSUE TITLE
Permission to add Caprice32 to Steam as free DLC for RetroArch

### ISSUE THREAD

**Issue by twinaphex** [ColinPitrat/caprice32#143]
Hi there,

we would like to seek your permission to include Caprice32 as a core as free DLC for RetroArch on Steam.

The user would have to manually install this, it would be freely made available.

If there's anything you are unsure of or are hesitant about, don't hesitate to bring it to our attention. We will always go with whatever you decide

**Comment by ColinPitrat** [comment]
Sure, no problem. Please ensure the name, licence information and a URL are provided.

**Comment by twinaphex** [comment]
Thank you! Will do. Is there an email address I could contact in the future too ?

**Comment by ColinPitrat** [comment]
It's fine to open an issue on github for any matter :-)
Don't hesitate to update this one (even after it's closed) to provide update on the inclusion in RetroArch on Steam.
