### ISSUE TITLE
Loading Disks / Tapes / Cartridges

### ISSUE THREAD

**Issue by bernhardsturm** [ColinPitrat/caprice32#144]
I don't know if this is the right place to comment or maybe suggest something new to Cap32.

I have built a version for Raspbian (on a Pi4), and set it up, so that it boots directly into Cap32 emulating a CPC6128. This set up works perfect, and I wanted to congratulate all of you for this fantastic emulator which brings back so many good memories.

However, I am struggeling when it comes to load disks, tapes or cartridges. 

I've found, that it is not possible to load media through `cat` and `run"xxx.dsk` via the CPC6128. As far as I understand the documentation, any software to be loaded, and run, has to be specified via CLI parameter when launching cap32. (at least I did not succeed to cat something without getting a CPC error message, that there is no disk in drive a: (retry, ignore or cancel))

In my set up I have an USB-stick which acts as a cartridge. My intention was, that if the USB-stick is present at `/media/pi/cartdridge/`, cap32 would detect the content (as the path to the stick is defined in the cfg-file), and then upon boot would try to run the content cartridge... however, this doesn't seem to work that way.

Would it be possible, to modify the cap32 emulator in such a way, that the defined paths in the cfg-file to disk, tape and cartridge would indeed define the physical drives, and the contents of those drives could then be retrieved and launched through `cat` or `run"` commands through the emulator directly like they would indeed be physical drives. Basically: emulate a real physical CPC machine.
What do you think?

P.S. I am running Cap32 under a German keyboard layout. I intend to provide a keymap for German keyboards, and contribute this map to the project.

**Comment by ColinPitrat** [comment]
Short answer, I'll make a longer one when I reach a computer. You can press F1 to reach a menu from which you can load cartridges and disks. You can also use a joystick button for that and navigate the menus entirely with the joystick.

**Comment by bernhardsturm** [comment]
Thanks for the reply... If I do a '**cat**' I always get:

```
Drive A: disc missing
Retry, Ignore or Cancel?
```
In my cat32.cfg I have:
```
[file]
max_track_size=5990
snap_path=./snap/
snap_file=
snap_zip=0
drvA_path=./disk
```
And the directory structure is:
```
caprice32
  disk
   Ghostbusters (UK) (1985).dsk
```
sorry to bother you with such trivial issues....

**Comment by ColinPitrat** [comment]
Did you load the .dsk file from the UI or did you provide it on the command line?
The drvA_path just provides the default directory in which the GUI will put you when you want to load a .dsk

**Comment by bernhardsturm** [comment]
Ah, that my be the issue... I assumed that you could simply put a DSK file in the specified directory (just like you would insert a physical disk), and then you could access it through the CPC with CPC commands like **cat**, **run"**.

I never tried it through the CLI, and on the UI (F1) I don't see that the two combo-selectors are populated with the games I put in the /drive/ directory.

This means, that it is not possible to have a couple of USB-sticks each holding its own cartridge game (CPR), which you could insert into a USB port, and then boot the Raspberry, and the game would start to play like on a real CPC. 
I planned to re-build a CPC on a Raspberry for my kids so that they could interact and learn the basics of computing on a very simple and reliable platform. It has to be as simple as possible.

**Comment by ColinPitrat** [comment]
It could be possible to autoload if there's a single file. One problem is just that it's a huge waste to put a single dsk file on a USB stick. The typical way to use caprice is either to load from the menu or to use a shortcut per game (for example in a media center menu).

**Comment by bernhardsturm** [comment]
Now it works... sorry for my blindness: the process is as follows:

1. Put a game image into the specified directory (specificed in cap32.cfg)
2. UI: Press F1, Load the game through [LOAD / SAVE], select the drive, the source, and press [LOAD]
3. On the CPC type cat: the content of the loaded disk is shown
4. Type run "[NAMEOFGAME]

So this is it, and I can perfectly live with this process very well ;-) 
Sorry again to bother you all with this trivial stuff.

**Comment by symbios24** [comment]
> Now it works... sorry for my blindness: the process is as follows:
> 
> 1. Put a game image into the specified directory (specificed in cap32.cfg)
> 2. UI: Press F1, Load the game through [LOAD / SAVE], select the drive, the source, and press [LOAD]
> 3. On the CPC type **cat** and the content of the loaded disk is shown
> 4. Type **run "[NAMEOFGAME]**
> 
> So this is it, and I can perfectly live with this process very well ;-) Sorry again to bother you all with this trivial stuff.

Hello,how did you build the raspberry pi version??

As i don't know what depends to install and what i do after??
Thank you
