### ISSUE TITLE
German keyboard mappings missing

### ISSUE THREAD

**Issue by zackizacki** [ColinPitrat/caprice32#145]
Caprice32 is not yet usable with german keyboards as  []{}+:;@| usually on the right keyboard side can not be entered at all.

I was able to add a debug message in cap32.cpp:2029 to figure out the correct keycodes for german keyboards and created a german keymap. Also Y and Z are correct now so that the games can be played with it.

[keymap_de_linux.map.zip](https://github.com/ColinPitrat/caprice32/files/4300958/keymap_de_linux.map.zip)

I hope next release comes with this file included. The windows part is missing, but maybe I can do it as well..

**Comment by ColinPitrat** [comment]
I added it to the repository.
Thanks!
