### ISSUE TITLE
Increase gui font size from 8pt to 11pt.

### ISSUE THREAD

**Issue by zackizacki** [ColinPitrat/caprice32#146]
Caprice32 has a wonderful OSD-GUI for the settings that can be reached with F1 key.
Really outstanding!
The only problem I have is, that the used font is so tiny that it somehow gives the whole thing a negative touch. I understand I can easily do a full screen, but even then the font really looks improper small (and also unsharp and fuzzy).

**Comment by ColinPitrat** [comment]
We could have an option for that.

Currently, just setting the size to 10 is almost OK (text overflows in a few places). Setting it to 12 result in something unreadable. So we would have to adjust some things and probably only accept a fix set of values.

**Comment by zackizacki** [comment]
I just figured out the video plugins and that they also affect the OSD Gui and its readability.
Would it be better to draw the OSD on top of the filtered/processed CPC-Screen instead to ley the filter on top of both CPCScreen and OSD so that the OSD always looks same?

**Comment by zackizacki** [comment]
The reason why I created this is because the 8pt font size is especially bad on linux debian10. I haven't figured it out yet why. I added screenshots on how a 10pt font size improves the situation dramatically. I'd propose to go with 10 pt on linux and fix the about box.
[fontsize.zip](https://github.com/ColinPitrat/caprice32/files/4332117/fontsize.zip)

**Comment by ColinPitrat** [comment]
Increased the size to 10pt and adapted all UI elements to the new size.
