### ISSUE TITLE
Delay between keystroke

### ISSUE THREAD

**Issue by Leopounet** [ColinPitrat/caprice32#147]
Hi,

I Don't know if it is the correct place to ask about that, so let me know if there is a better place.
I'm trying to use Caprice32 to create a new environment for OpenAI Gym. To do so, one of the things I need to be able to do is to send keystroke via SDL to Caprice32.

```
SDL_Event sdlevent;
sdlevent.type = SDL_KEYDOWN;
sdlevent.key.keysym.sym = code;
sdlevent.key.keysym.mod = mod;
SDL_PushEvent(&sdlevent);
// Do one loop of the main while loop
```

That's the idea of how I'm doing it, but the problem is that Caprice32 won't let me send too many inputs too quickly, it won't register them all. I read in some comments that there is an artificial delay or something but can't clearly understand what it is about. Do you know how to work around this problem? So far, the best thing I can do is run the main loop a few thousand times before sending another input, which isn't great. I don't mind the waiting but I'd like to know if there is a method or a define or anything else that can wait the exact amount of time required. (hopefully that makes sense)

Also, I was wondering, is there a method I can call to simulate the "run"<game>" command?

**Comment by zackizacki** [comment]
As I remember the cpc is polling the keyboard wires via interrupt 50 times per second.
If the key events are not processed that fast by the game then the key strokes 
are stored in a buffer, up to 20 keystrokes.

Maybe you should simplify your approach:

For example: to stear the car to the right you just want to send one keydown event, hold it for a while (do nothing) and send a keyup, when the turn is just right (visually) after 100ms or so. The same with plaform games.

To increase overal learning and simulation speed, you just might want to run caprice without speed limitation (not in realtime, at 2000% etc). 

I hope this helps.

you can use the feature autocmd like this to automatically type some input after initialization:

C:\Daten\dev\caprice32>.\cap32 --autocmd "run\""

**Comment by Leopounet** [comment]
Thank you for you reply. 

If I run Caprice32 without any speed limitation, every input will be processed, without being buffered, right? That might be a solution. Also, you're idea of using a timer is great, I can't believe I didn't think about it. 

I didn't realize there was this argument, it must do exactly what I need, thanks!

**Comment by ColinPitrat** [comment]
I'm interested by the result, keep us updated. If you need to request or contribute some changes to better integrate with OpenAI Gym, don't hesitate.
