### ISSUE TITLE
Isolate #defines _C _B _A _L etc from z80.h into z80.cpp

### ISSUE THREAD

**Issue by zackizacki** [ColinPitrat/caprice32#150]
I tried to compile caprice with mingw-w64 and msys2.0 which failed.

Macros like _C and _B are usually reserved for compilers. 
Some define those in ctype.h and then caprice won't compile with such compilers.

It is for future compatibility only.

1. move the problematic one letter #defines from z80.h into z80.cpp
2. move the code that uses _A etc in cap32.cpp:974 into a new method z80.cpp/z80_reset().
3. make sure z80.cpp does not include <string.h> and thus ctype.h.

**Comment by zackizacki** [comment]
Meanwhile I could figure out how to exactly create a windows release with msys2/mingw64. Indeed I ran into several little issues because I did not have a documentation to follow.

So this can be closed and my pull request could also be parked in a branch or what without merge , i don't mind.

The build process is a masterpiece by the way, although it could deserve some more comments about the mechanics, but it is really good.

Maybe I could make some notes, what worked for me to build on Windows10 with mingw-64 and you can check if its worth to add to the documentation?

Also, the build on my debian10 main machine was working just out of the box without any trouble which could also be worth to mention in the documentation.

**Comment by ColinPitrat** [comment]
The build on AppVeyor is using msys2 and mingw-w64 and works fine, but I agree that leading _ in variables and macros is a bad thing as they are reserved for the C++ implementation.

**Comment by ColinPitrat** [comment]
I welcome any addition to the documentation on the topic! :-)

**Comment by zackizacki** [comment]
We have some basic separation that could help to get around future problems and we have one TODO in the code. So I'd propose this ticket.
