### ISSUE TITLE
Arrow characters on mouse move

### ISSUE THREAD

**Issue by bert003** [ColinPitrat/caprice32#17]
I noticed that when the mouse pointer is moved and caprice32 is open, arrow characters are typed as shown below. Not sure if it is a Virtualbox related issue though.

![capture](https://cloud.githubusercontent.com/assets/20399702/16898781/0f251cba-4be9-11e6-9f6e-7a0cb0cef02f.jpg)

**Comment by ColinPitrat** [comment]
I've never observed that but this are the characters that are displayed when using a joystick. This may be linked to the mouse device from VirtualBox being recognized as a joystick by SDL.

If you don't use joysticks, you can deactivate it by changing the value of joysticks from 1 to 0 in cap32.cfg:
joysticks=0

For information (unrelated to this bug but nice to know), caprice32 also supports joystick emulation in case you encounter a game that requires joystick. It can be activated/deactivated by pressing F7. It makes the arrows and Z and X (or W and X on french keyboard) to replace joystick controls.

**Comment by bert003** [comment]
Thanks for the detailed information.

Just wanted to confirm that it was due to the joystick emulation as you correctly suspected.

In fact I remember way back that those characters used to appear as well on my physical Amstrad when the joystick was pressed.

Deactivated the joystick and now all is fine.
