### ISSUE TITLE
Compile  WITH_IPF=true fails due to missing "caps/capsimage.h"

### ISSUE THREAD

**Issue by 2play** [ColinPitrat/caprice32#170]
Compile with  "make APP_PATH="$PWD" WITH_IPF=true ARCH=linux -j 4" :  Fails with below errors

```
In file included from src/ipf.cpp:16:
src/ipf.h:7:10: fatal error: caps/capsimage.h: No such file or directory
 #include "caps/capsimage.h"
```

```
In file included from src/ipf.cpp:16:
src/ipf.h:7:10: fatal error: caps/capsimage.h: No such file or directory
 #include "caps/capsimage.h"
```

**Comment by 2play** [comment]
Found workaround by doing this:
I ve extracted from this ipflib42_linux-x86_64.tar.gz the caps folder (attached) and copied over to
`/usr/include`

[caps.zip](https://github.com/ColinPitrat/caprice32/files/4770129/caps.zip)

The compiled fine with above command.

```
./caprice32/cap32 -V
Caprice32 v4.6.0-40abd2a6f0e00d9cdfc5265907c86c0d146acfb5
APP_PATH: Not provided
Compiled with: HAVE_GL WITH_IPF
Number of video plugins available: 12
```

**Comment by ColinPitrat** [comment]
This is WAI.
The licence for IPF support doesn't allow us to include the code in Caprice. The end-user has to download it themselves and agree with the terms.
cf https://github.com/ColinPitrat/caprice32/blob/master/INSTALL.md#ipf-support
