### ISSUE TITLE
Windows 64 bit release missing file libbrotlidec.dll so program will not run.

### ISSUE THREAD

**Issue by riwide** [ColinPitrat/caprice32#173]

**Comment by ColinPitrat** [comment]
This is now fixed.

**Comment by ColinPitrat** [comment]
Ideally we would need a test for this.
I suppose the end-to-end test doesn't catch it because it finds the DLL locally.

**Comment by riwide** [comment]
thanks

**Comment by ColinPitrat** [comment]
Note: I temporarily reverted the fix to try to write a test that detects the issue.
It turns out quite hard because the DLL are found on the system ...

**Comment by ColinPitrat** [comment]
I opened issue 174 to track writing a test for this.
