### ISSUE TITLE
Feature request: program auto injection from command-line

### ISSUE THREAD

**Issue by leuat** [ColinPitrat/caprice32#175]
Hi there!

I'm the developer of TRSE (Turbo Rascal Syntax Error), see www.turborascal.com or https://github.com/leuat/TRSE, a cross-platform development compiler & IDE for several 8/16-bit computers. I've recently implemented a rudimentary Z80 compiler, and was hoping to add support for the Amstrad CPC - but I'm having problems finding an emulator that lets you auto-inject a program into the emulator memory from command line (and then start the program). This is a common feature in emulators such as Vice, Mednafen etc, and greatly improves the usability of the emulator in an IDE framework, since you don't have to go through the hassle of creating disk files & issuing commands etc.

I'd *really* appreciate if cap32 could get this feature implemented - streamlining the development process for the CPC. Example:  "./cap32 -inject myProgram.bin $6000"

**Comment by AndyHOvine** [comment]
+1 for this feature, if I can use TRSE to develop on the Amstrad :)

**Comment by ColinPitrat** [comment]
That sounds feasible and interesting. Could you attach an example of such a program so I that I can test? (A simple hello world would do)

**Comment by leuat** [comment]
[fill.zip](https://github.com/ColinPitrat/caprice32/files/5014931/fill.zip)

Nice, that would be amazing! 

"fill.prg" starts at $6000. 

disk1.dsk simply contains the fill.prg program in order to test that it works.

**Comment by leuat** [comment]
[fill2.zip](https://github.com/ColinPitrat/caprice32/files/5014967/fill2.zip)
hm. looks like the .prg file has a header attached to it... if it doesn't work, then please try this file (fill.bin, should be no header)

**Comment by ColinPitrat** [comment]
You can give it a try:

```
cap32 -i fill.bin -o 0x6000
```

**Comment by leuat** [comment]
Thanks a bunch! *so* much faster to compile -> run program in TRSE now. See for yourself : https://www.irio.co.uk/L/amstrad1.mp4

**Comment by leuat** [comment]
Any chance to get quick windows release? While I use Linux, most of the TRSE testers are on windows...

**Comment by ColinPitrat** [comment]
The Windows release normally happens automatically at each commit and take ~20mn but msys2 setup is currently broken due to invalid certificates. I'll look deeper tomorrow, I'd expect the issue to have already been reported so it maybe fixed soon.

**Comment by ColinPitrat** [comment]
Note to self to dig tomorrow:
https://help.appveyor.com/discussions/problems/27815-build-failing-due-to-key-error

**Comment by ColinPitrat** [comment]
The windows build is available now.

**Comment by AndyHOvine** [comment]
Brilliant. Thank you Colin. I will test this out with TRSE at lunchtime. I’ve started writing some units using snippets of code I’ve found online, such as joystick input and setting screen modes with crtc. Being able to inject code right in will make this so much quicker to do. 

Very much appreciated!

**Comment by AndyHOvine** [comment]
Tested the Windows build with the injection update in TRSE and works great.

**Comment by ColinPitrat** [comment]
Excellent.
Thanks for making me discover TRSE.
When will the CPC integration be available in the linux build?

**Comment by AndyHOvine** [comment]
Leaut has the essentials in place right now.  It's still WIP.  You can find the basic Amstrad program in the Tutorials folder.  It just sets mode 0, 256 width and fills the screen at the moment. I'll be helping add support via Units and Leaut will expand the TRSE command support. If you have anything that can help, or would like to write any units you are very welcome to help out :) 

You will need pasmo assembler and point TRSE settings to it, and Caprice of course :)
