### ISSUE TITLE
Mouse wheel issue on controls with a scrollbar

### ISSUE THREAD

**Issue by AndyHOvine** [ColinPitrat/caprice32#178]
On the controls with a scrollbar such as the Video plug-in drop down (see below) or on the Load/Save list box, the mouse wheel can be used to scroll the view up and down, but only when over the scrollbar area.  When moving over the main part of the control, eg TV 2x area, the mouse wheel does not work.  This is tested on the Windows version.

Is it possible to enable the mouse wheel while over any part of the control?

![image](https://user-images.githubusercontent.com/710401/89708146-89370080-d96c-11ea-8328-9efe6c256d95.png)

**Comment by ColinPitrat** [comment]
Thanks for reporting this usability issue.
This should now be fixed.
