### ISSUE TITLE
Load / Save - navigating folders and scrollbar issue

### ISSUE THREAD

**Issue by AndyHOvine** [ColinPitrat/caprice32#179]
On the Load / Save, when I navigate directories

![image](https://user-images.githubusercontent.com/710401/89708263-46295d00-d96d-11ea-8c9c-0907e740070f.png)

If I click the Ovine folder, the list contents changes but the scrollbar position is incorrect.  When you move it, it snaps back to the top where it should be.

![image](https://user-images.githubusercontent.com/710401/89708277-7670fb80-d96d-11ea-9294-02947b7fb725.png)

This is a little confusion, could you update the scroll bar position to go to the correct place at the top when entering a folder?

**Comment by ColinPitrat** [comment]
Interesting, to occur this requires a directory in which you have to scroll down to find a directory that contains enough directories or files to require a scrollbar.
Note to self: A good test case for me is /tmp.

**Comment by ColinPitrat** [comment]
This should now be fixed.
