### ISSUE TITLE
Shifting 32-bit value by 32 bits is undefined behaviour. 

### ISSUE THREAD

**Issue by ZanyXDev** [ColinPitrat/caprice32#183]
https://github.com/ColinPitrat/caprice32/blob/584d4ab6f4ce178b0a83a6a2d95119213c86fda6/src/crtc.cpp#L843
see condition 
https://github.com/ColinPitrat/caprice32/blob/584d4ab6f4ce178b0a83a6a2d95119213c86fda6/src/crtc.cpp#L838

**Comment by ColinPitrat** [comment]
You mean in case byteShift > 8? The method is never called with this but indeed, we could replace
https://github.com/ColinPitrat/caprice32/blob/584d4ab6f4ce178b0a83a6a2d95119213c86fda6/src/crtc.cpp#L835
by

`
   if (byteShift >= 8) {
`
