### ISSUE TITLE
Tag consistency

### ISSUE THREAD

**Issue by bignaux** [ColinPitrat/caprice32#197]
Please, when you tag the repo, like sdl_v1 sdl_v2, don't delete them a few days after, because you're breaking my packaging then my repository on CI won't build because it can't fetch the tagged version ( https://github.com/bignaux/nur-packages/runs/2270790635?check_suite_focus=true ). I put a broken on this package for me, until next release; if you're unhappy with a release, release another one, increase tag version and please, don't remove previous tag since people rely on.

**Comment by ColinPitrat** [comment]
These were tags and releases that were not aimed to be consumed and were
flagged as draft on github. Is your automation picking up automatically the
last release ?

Le lun. 5 avr. 2021 à 16:55, Bignaux Ronan ***@***.***> a
écrit :

**Comment by bignaux** [comment]
I subscribe the watch release and github send me mail : 
```

Caprice32 sdl2_v1

Repository: ColinPitrat/caprice32 · Tag: sdl2_v1 · Commit: d93da37 · Released by: ColinPitrat
```
and i saw nowhere it was draft. i package with the latest tag since i found interesting to have SDL2. i donno was to tell if you thought you were doing a release that was not.

**Comment by ColinPitrat** [comment]
OK, I plan to release a 4.7.0 soonish but I got a few bug reports lately and would like to wait a bit more to avoid shipping obvious bigs.

**Comment by bignaux** [comment]
No worry, i was just a bit upset because it's in the air, cancel culture and so, the bad habits of clean everything in History.

**Comment by ColinPitrat** [comment]
Maybe I should have made it clearer in the release notes or in the tag name that these were not intended to last.
It's just the only way I have to make a windows release for people to test it :-) (the tag triggers a build and a release creation on AppVeyor)
