### ISSUE TITLE
Enable joystick from caprice32 options menu

### ISSUE THREAD

**Issue by bert003** [ColinPitrat/caprice32#20]
Can there be an option added to enable and disable the joystick from the F1 options menu?

Right now there isn't one (I couldn't find it) and to enable and disable the joystick you have to manually edit cap32.cfg.

I am working to produce a live cd to resemble the Amstrad functionality as much as possible (will keep you posted on this) and I am planning to include caprice32 as an emulator and obviously give you the credit you truly deserve. Like that the novice user would not need to edit config files manually.

Do I have your permission to use caprice32 for this project please? :-)

**Comment by ColinPitrat** [comment]
This issue and issue #8 should both be done at the same time.
Ability to configure joystick buttons in the GUI would also be nice.

**Comment by bert003** [comment]
Thanks a lot :-) I will for sure... still work in progress for now

**Comment by ColinPitrat** [comment]
This is done. An improvement over it would be to support choosing which physical joystick correspond to which CPC one (typically to use with one joystick and use joystick emulation for the other one, which is not possible currently) but I open a separate issue for this.
