### ISSUE TITLE
Problem with std::filesystem on gcc

### ISSUE THREAD

**Issue by NotFound** [ColinPitrat/caprice32#212]
Compiling the current version with gcc 8.3.0 gives me error with std::filesystem

Searching about the problem, I found that gcc needs to specify a library for its use, stdc++fs

To be able to add the library, I changed the 'LIBS = ...' to 'LIBS += ...' in the makefile

Then:
LIBS=-lstdc++fs make

builds it fine and works

**Comment by ColinPitrat** [comment]
This should be solved now.
Thanks for reporting the issue!
