### ISSUE TITLE
lightgun support

### ISSUE THREAD

**Issue by Huntsman360** [ColinPitrat/caprice32#214]
Is any possibility toi add support for lightgun Amstrad CPC's peripherals?

for games like target plus from dinamic

**Comment by ColinPitrat** [comment]
That's tracked by https://github.com/ColinPitrat/caprice32/issues/34
That's not extremely complicated to do but I've not considered it high priority so far.

It seems Target Plus relies on a different gun though.

**Comment by Huntsman360** [comment]
ok, i wrote mouse beacuse current guns use mouse. I like it to use my sinden lightgun

Best regardds and sorry

**Comment by ColinPitrat** [comment]
How does the Sinden lightgun appears to the computer? Is it like a mouse?
