### ISSUE TITLE
Load/save menu doesn't support zip files

### ISSUE THREAD

**Issue by ColinPitrat** [ColinPitrat/caprice32#22]
The load/save menu only supports loading .sna for snapshots, .dsk for disks, .cdt for tapes. It doesn't support loading .zip for all these kinds. It doesn't support loading .voc either for tapes.

Moreover, when giving a zip file on the command line, the load menu is broken for the corresponding file type due to xxxx_path being set to the zip file.

**Comment by bert003** [comment]
It would be nice to have this enhancement however I do not consider it as a major issue. Everyone knows how to extract the contents of zip files nowadays and cpc games are so small in size that there is no need to compress them.

Anyway, the more features, the merrier :-)

Thanks

**Comment by ColinPitrat** [comment]
This is now fully implemented even though some cleaning remain to be done (reflected by TODO in the code). Closing this issue.
