### ISSUE TITLE
Virtual Keyborad

### ISSUE THREAD

**Issue by Korben34** [ColinPitrat/caprice32#220]
Hello, 
I use [aarch64](https://github.com/christianhaitian/retroarch-cores/tree/master/aarch64)/cap32_libretro.so to build .UCE files of my best .DSK images to play CPC games on the Atgames Legend Ultimate arcade. Games can be launched but how to access to the virtual keyboard (which is mandatory to play or to answer game questions ?, etc.). Seems not to be possible ... ?
Thanks

**Comment by ColinPitrat** [comment]
I'm not familiar with libretro, that'd be something to ask them.

On vanilla caprice32, the virtual keyboard is accessible via:
- button number 10 on joystick by default (configurable in configuration with system.joystick_vkeyboard_button
- Shift + F1 from keyboard (obviously less useful if you don't have a keyboard but useful when your keyboard is missing some keys, e.g no keypad and need of Fx keys)

**Comment by Korben34** [comment]
Thank you for the advice

**Comment by DSkywalk** [comment]
You have cap32 libretro with the documentation on his github: https://github.com/libretro/libretro-cap32/blob/master/README.md :+1: 

As you can see you could use F9 or SELECT+START (configurable via options menu)
