### ISSUE TITLE
Bad memory configuration - fix

### ISSUE THREAD

**Issue by DSkywalk** [ColinPitrat/caprice32#221]
Hello Colin! :call_me_hand: 

Yesterday we fixed this problem that freezes original release of Heroquest (CRC: EC279622), it's a bug that's been hiding there all these years:
https://github.com/libretro/libretro-cap32/commit/467c4fefb7c861d14be88760ee421d99897e65d9

more info (in spanish sorry): https://twitter.com/dskywalk/status/1502938646785282050

Take care and best regards mate! :+1:

**Comment by ColinPitrat** [comment]
Thanks, very interesting!

I'll see if this solves some of the unsolvable issues I had :-)

From http://cpctech.cpc-live.com/docs/rampage.html

> The ram paging register is accessed when bit 15 of I/O address is set to "0". This register is write only and cannot be read. This register shares the same I/O address decoding as the Gate-Array, but uses a unused function to avoid conflict.

To be compared with the Gate Array (https://www.cpcwiki.eu/index.php/Gate_Array):

> The gate array is selected when bit 15 of the I/O port address is set to "0" and bit 14 of the I/O port address is set to "1". The values of the other bits are ignored. However, to avoid conflict with other devices in the system, these bits should be set to "1".

**Comment by DSkywalk** [comment]
Happy to read you Colin! :D

The biggest thanks go to @jcgamestoy, who helped and guided me when I detected the problem in order to solve it :tada: 

You've documented it brilliantly, I'll add it to my next update. Best regards!!
