### ISSUE TITLE
swap disc problem

### ISSUE THREAD

**Issue by kounabi22** [ColinPitrat/caprice32#225]
When a game ask me to change side b and i try to swap disc i get an error 
"failed to append disc" and the game dont continue

**Comment by ColinPitrat** [comment]
Can you provide more details? What game? How do you swap disk?

**Comment by kounabi22** [comment]
well in all games that ask to put side b,,, 
found a solution by using m3u files and add the name of the files in the m3u.
EmulationStation dont see the m3u files but i can open the m3u file from retroarch menu.

**Comment by ColinPitrat** [comment]
Is this an issue with Caprice32 or is it specific to retroarch?

**Comment by kounabi22** [comment]
as far i have read in othe forums must be retroarch ..it happend in other emulators

**Comment by ColinPitrat** [comment]
I'll close this as this doesn't seem to be a Caprice issue.

**Comment by DarkCTO** [comment]
Any chance cap32 would support multi .dsk in one zip ?
