### ISSUE TITLE
Bug in F1 Menu

### ISSUE THREAD

**Issue by bert003** [ColinPitrat/caprice32#26]
I set model=3 and the cartridge loads correctly.

However, I pressed the drop down from the menu to select a cpc model and then DID NOT select one (just clicked somewhere else) and closed the menu.

Pressed F10 to restart and the normal 128K Basic 1.1 screen loaded.

Took a look at cap32.cfg to find model set to -1.

**Comment by ColinPitrat** [comment]
Yes I noticed that already :-) This will be fixed once I add the support for the plus in the menu (i.e as soon as plus support is good enough to be made available, even if a few stuff are missing)

**Comment by bert003** [comment]
That's great! Cheers :-)

**Comment by ColinPitrat** [comment]
I added an entry for CPC 464+, despite the support being far from complete, which fixes this bug.

**Comment by bert003** [comment]
Thanks a lot... for clarity purposes can you name it _cpc plus_ since my Amstrad back in the good old days was a 6128 plus and was exactly this same cartridge with Burnin' Rubber. What do you think?

Sorry but I am a bit OCD in these things :-)

**Comment by ColinPitrat** [comment]
In fact I rename it 6128+ because that's what it emulates currently (128k of RAM and a disk drive). To support the 464+ I need to limit to 64k and deactivate the disk drive.

**Comment by bert003** [comment]
Still model is being set as -1 instead of 3 in the config file...

**Comment by ColinPitrat** [comment]
It shouldn't. Are you sure it's not a leftover ?

**Comment by bert003** [comment]
No. In fact when you restart the emulator after you set it,  the emulator resets back to 6128. I am always doing a fresh clone and recompile to be sure that all changes are pulled.

**Comment by ColinPitrat** [comment]
If you press Save it modifies cap32.cfg. If you press Apply it only impacts the current run.
Are you sure you have the last version cloned ? And the cap32.cfg doesn't contain model=-1 to start with ? For me it's working as expected.

**Comment by bert003** [comment]
Works as expected now as well. Maybe I forgot to pull the latest updates before compiling. Not sure what happened though. Sorry about that.

**Comment by ColinPitrat** [comment]
No problem, it happens :-)
