### ISSUE TITLE
Document joystick emulation

### ISSUE THREAD

**Issue by bert003** [ColinPitrat/caprice32#27]
In VirtualBox, loading the cartridge (model=3) with joystick enabled results in a series of continuous beeps as if I am pressing the joystick buttons. The beeps are gone once the joystick is disabled (hence my suggestion earlier to be able to disable the joystick via the menu)

Also, having no joystick and operating a laptop, I could not find a way to play Burnin' Rubber. Only F and G keys work and I have no joystick controls. It would be nice if there was a way to map arrow keys to joystick directional controls and any other 2 keys to joystick buttons. I think this is doable since I saw another other emulator (I guess it was WinAPE) that managed to achieve such an option. What do you think?

Is it too much of a problem? Hope I am not bugging with all these issues but I am being your personal tester :-)

**Comment by ColinPitrat** [comment]
There is a way: joystick emulation. I didn't test it with Burnin' Rubber but I don't see why it wouldn't work.
Just press F7. Then arrows and Z/X (or W/X on french keyboard) replace the joystick arrows and A/B.

The issues are cool, it's nice to see someone using the soft and having feedback is great.
Having someone else using it allows to test all the cases I never even thought of testing (like the close button of the virtual keyboard :-)) so it definitely helps improving the soft. Thanks for opening them, please continue doing so each time you find something that bother you. Even issue like this one (where the functionality exist) are useful by reminding me that I should write doc and helping me prioritize topic.

**Comment by bert003** [comment]
Thanks for the tip...

Being a programmer myself I know how helpful it is to have someone else testing the software for you... Bugs which you never though existed will pop up in no time :-)

Yes, documentation is definitely necessary and I can them include it in the live system as well. I can help with that if you want :+1:

**Comment by ColinPitrat** [comment]
Issue 39 is clearly a super set of this one.
