### ISSUE TITLE
Support loading cartridges

### ISSUE THREAD

**Issue by ColinPitrat** [ColinPitrat/caprice32#30]
Currently the only way to load a cartridge is to pass it on the command line.
This should be added to the load/save menu.

**Comment by bert003** [comment]
Yes that would be great especially for the average user who would not want to mess around with configuration files manually :+1:

**Comment by ColinPitrat** [comment]
You do not need to put it in configuration file, you can give it on the command line. For example `./cap32 cartridge/tintin.cpr`.

**Comment by bert003** [comment]
Ok agreed but in my live system, the emulator is set to load automatically on start of X as if you had a proper Amstrad... so the user will not be given access to a console...
