### ISSUE TITLE
Black screen on emulator reset (F5)

### ISSUE THREAD

**Issue by bert003** [ColinPitrat/caprice32#33]
It does not happen all the time but sometimes I press F5 and I get a black screen.

The emulator is there but nothing is shown. I know the emulator has loaded since when I press F10, it quits successfully.

Cannot tell what is wrong and have no idea in mind how to, sort of, debug it...

Sometimes also the emulator displays a black screen immediately and does not load. I cannot press F10 to quit which means it is not responding and I am forced to kill it from another terminal...

CPU usage is also high all the time when it is running...

![capture](https://cloud.githubusercontent.com/assets/20399702/17203817/d9b98ebe-54a1-11e6-8963-74ff1704cc13.jpg)

**Comment by ColinPitrat** [comment]
The 100% CPU is only when you have the issue right ?
I never observed the same behaviour, I'm not sure how to get more info on it. You can try attaching with gdb and getting a stack. To do this: `gdb -p <pid>` (here the pid is 800, first number on your screenshot) then once in gdb, type `bt`. 

With a release build, this will give a stack with limited information so it would be better if you manage to obtain it with a debug build. But on the other hand, this may happen only in release mode which would explain why I never observed it ...

**Comment by ColinPitrat** [comment]
Hmm, I did manage to reproduce with a release build. 
Taking different stacks shows that the emulator keeps running, but some part may be skipped.
I don't manage to reproduce the issue at startup however. Maybe these are 2 different problems.

**Comment by bert003** [comment]
The 100% CPU usage is always there once the emulator is running. Check below:

![shot1](https://cloud.githubusercontent.com/assets/20399702/17211193/43e2c514-54c8-11e6-9f37-715b2eb883c6.jpg)

In fact I started the emulator twice on tty1 and tty2 and it was showing 628%!!

![shot2](https://cloud.githubusercontent.com/assets/20399702/17211200/4e5c990c-54c8-11e6-8185-6915b41ac87c.JPG)

I always test in release mode.

**Comment by ColinPitrat** [comment]
This percentage is not the CPU usage, it's the speed at which the emulator is running compared to the normal speed of a CPC. By default, the speed is capped (limit_speed=1 - this is not part of cap32.cfg) and you should always see 100% +/- 1 or 2, unless your computer is too slow in which case you will have a lower value (this can happen or very old hardware or if your computer is very loaded).

If you press F9, this toggles limit_speed. When limit_speed is 0, the emulation is simply as fast as your computer can do which can reach very high values on modern computers. 

This has not much interest for the end user (unless you want to exercise your reflex by playing at ultra-fast games) but this is nice to observe the effect of optimizations or verify that changes in the code don't reduce the performances.

**Comment by ColinPitrat** [comment]
Concerning the bug, I have a very good news: this should be fixed.

I managed to reproduce it systematically: with CPC 6128+, launch burnin' rubber and just when "Prepare to qualify" is shown, press F5. After my fix that I just pushed, this works correctly. 

The bug doesn't explain the other issue you described:

> Sometimes also the emulator displays a black screen immediately and does not load. I cannot press F10 to quit which means it is not responding and I am forced to kill it from another terminal...

For this one, if it occurs, could you try the `gdb -p <pid>` and then `bt` if it reoccurs ? Doing it multiple time can help identify whether the emulator is stuck (which is probably the case if F10 doesn't exit) or not. The trick I use for this is to do the following commands:

`for i in $(seq 1 30); do echo "y" | gdb -p $PID | grep -C 1 "^#" > stack_${i}.txt; done`

which launch 30 times gdb, dumping the stack in a different file each time.
and then:

`md5sum stack_* | sort`

which compute a checksum of each file and group them. This helps identifying quickly which ones are identical. You can then open/attach to this bug one of each type.

**Comment by bert003** [comment]
Thanks for the detailed information and for taking the time to identify and fix the bug. Recompiled and tested successfully.

I am using 2 CPUs (cores) for VirtualBox and below is the CPU usage in _top_ with Irix mode On.

![cpuusage](https://cloud.githubusercontent.com/assets/20399702/17237952/bde7e1ca-5557-11e6-8a5f-44b09ba8d32b.jpg)

With Irix mode Off it drops to half the value. Is that normal please?

I will do as you instructed if the emulator does not load immediately and post updates.

**Comment by ColinPitrat** [comment]
The drop is normal:
http://unix.stackexchange.com/questions/15733/why-process-cpu-usage-larger-than-total-cpu-time

**Comment by bert003** [comment]
Ok thanks

**Comment by ColinPitrat** [comment]
I'll close this one, please open a new one if you reproduce the failure at init.
Thanks.
