### ISSUE TITLE
Automatically pause when loosing focus

### ISSUE THREAD

**Issue by ColinPitrat** [ColinPitrat/caprice32#47]
This is the auto_pause option that is currently unimplemented.
I guess this may have some value but unless someone asks for it, this is low priority ...

**Comment by sebhz** [comment]
SDL2.0 seems to have the proper API to check window focus, which would make this a breeze to implement... but I am not sure migrating Caprice32 to SDL2.0 is pretty high in the priority list :-)

**Comment by ColinPitrat** [comment]
Not really. I tried it for clipboard support (could have been useful for memory tool) but there's a lot of work to do. Moreover SDL 2.0 is less available (e.g old Debians ...) even though this argument is getting less and less true.

**Comment by ColinPitrat** [comment]
Note that there's some support in SDL 1.2 too:
https://www.libsdl.org/release/SDL-1.2.15/docs/html/sdlactiveevent.html

The one we would need is probably SDL_APPINPUTFOCUS

**Comment by sebhz** [comment]
Neat. I'll have a look at this after cleaning up a few things in the latest code. Lots of things missing in the man page for one.
