### ISSUE TITLE
Problem with zip file handling when compiling under MSYS2/mingw64

### ISSUE THREAD

**Issue by sebhz** [ColinPitrat/caprice32#66]
MS Windows binaries compiled with windows under MSYS2/mingw64 cannot open zipped disk files.
After some investigation, it turns out the zip::extract method creates corrupted files (duplicated bytes here and there in the decompressed file vs the original .dsk).
The exact same routine works just fine under Linux, and probably fine when cross-compiling for Windows under Linux. This is not a big problem, but something that needs a bit of investigation.

**Comment by ColinPitrat** [comment]
I managed to reproduce it with wine with my builds.
The issue is that '0xa' is replaced by '0xd 0xa' (or with escape char, '\n' is replaced by '\r\n').
It means the file is treated as a text one when it should be treated as a binary one.

**Comment by ColinPitrat** [comment]
I submitted a fix (https://github.com/ColinPitrat/caprice32/commit/fda0e06237a5627900ffc4da698f1861de84f2ac) but I cannot test it right now. You can give it a try.

**Comment by sebhz** [comment]
I actually had done the exact same fix 2 minutes ago on my side. It works :-)

**Comment by ColinPitrat** [comment]
BTW, not sure if you saw the update in #11 
I did some modifications in windows build. If you have ideas for the last item (automatic validation of windows build & unit tests as is done for linux in travis) that would be very nice.
