### ISSUE TITLE
Opening Menu makes caprice crash when video mode is OpenGL

### ISSUE THREAD

**Issue by ColinPitrat** [ColinPitrat/caprice32#7]
With caprice using OpenGL mode, pressing F1 to open the menu makes caprice crash.

Stack is the following:

```
#0  0xb7ace693 in _int_malloc () from /usr/lib/libc.so.6
#1  0xb7acf8f5 in malloc () from /usr/lib/libc.so.6
#2  0xb7f22be7 in SDL_CreateRGBSurface () from /usr/lib/libSDL-1.2.so.0
#3  0x080e236f in wGui::CWindow::CWindow(wGui::CRect const&, wGui::CWindow*) ()
#4  0x080de2b8 in wGui::CView::CView (this=0xbffff778, surface=0x86cb080, backSurface=0x840bd48, WindowRect=...) at gui/src/wg_view.cpp:77
#5  0x08086d12 in CapriceGuiView::CapriceGuiView (this=0xbffff778, surface=0x86cb080, backSurface=0x840bd48, WindowRect=...) at gui/src/CapriceGuiView.cpp:175
#6  0x08057326 in main (argc=1, argv=0xbffffa84) at cap32.cpp:4662
```

There's no direct call to SDL_CreateRGBSurface in CWindow::CWindow, but CWindow::CWindow calls CWindow::SetWindowRect that calls SDL_CreateRGBSurface.

**Comment by ColinPitrat** [comment]
Occurs on my Asus Eee PC, not on my X1 Carbon

**Comment by sebhz** [comment]
With the very latest head (0dae266e44f502ee0c877e6e71e822528ba68595), the menu works just fine for me, when using OpenGL plugin.
It gets rendered with scanlines, which adds a nice vintage flavor to it IMHO.
Tested under Ubuntu 16.10 and MS Win8.

**Comment by ColinPitrat** [comment]
The issue seems to be fixed for me to. I don't remember whether I did something to fix it.
It may have been an issue with a given version of OpenGL that was solved by an update.
Closing this bug.
