### ISSUE TITLE
Wrong keyboard mapping

### ISSUE THREAD

**Issue by sebhz** [ColinPitrat/caprice32#75]
On my french laptop (french keyboard) under MS windows (French keyboard declared in Windows): keyboard mapping is correct. Using an external English keyboard with under an English MS Windows (and setting proper mapping in Caprice32 -> kbd_layout = 0), keys are all wrong, and even the virtual keyboard seems t output wrong characters.

**Comment by ColinPitrat** [comment]
Did you change both keyboard and kbd_layout ?
Both have to be inline for it to work. I'm not sure if there's a huge benefit of having the ability to not have them aligned btw !

**Comment by sebhz** [comment]
Yes I did. Both keyboard and kbd_layout are aligned.
Keyboard mapping and SDL has always been a nightmare for me BTW not even on Caprice32, it is high time I try and sort this out for good !

**Comment by sebhz** [comment]
Just did a quick trial home: on my home laptop (Win10), french keyboard, Windows locale set to FRA, both keyboard and kbd_layout set to 1 (French), Typing AZERTY in Caprice32 shows QWERTY in the emulator :-)

**Comment by ColinPitrat** [comment]
I don't have this issue under wine, I'll try with a native windows.
However, under wine, the double quote (") doesn't work whereas it does under linux. I suspect this has something to do with modifiers, I'll do more testing.

**Comment by sebhz** [comment]
Just did a few trials... when I press "A" on my French AZERTY keyboard (under MS Windows), the event.key.keysym.sym I get is SDLK_q. And of course, when I press "Q" I get SDLK_a.
It looks like a known (albeit pretty old) issue.
See for example [this old post](http://codes-sources.commentcamarche.net/source/50130-qwerty-azerty-avec-sdl-une-alternative). I am a bit reluctant to go Unicode - though it would probably simplify things a lot: only have one CPC.keyboard map to describe the CPC keyboard, let the user type whatver he wants on his keyboard and convert the keypresses to the right CPC codes (if they exist in the CPC keyboard chosen). Your advice ?

**Comment by ColinPitrat** [comment]
As the SDL documentation describes, the event contains both scancode and keycode. Scancode corresponds to the physical key pressed whereas keycode should depend on the layout (hence SDLK_a when you press "A").
https://www.libsdl.org/release/SDL-1.2.15/docs/html/sdlkeysym.html

The problem with the "unicode" solution is that it won't work for all keys so we would need a hack for special keys anyway (e.g: arrows). Moreover I'm not sure it would be able to differentiate numpad (mapped to function keys of the CPC) from the numbers.

I think we need to go to the end of the problem before settling for a solution.
Do you have the problem after restarting the emulator ? I noticed that there seems to be a bug when changing the keyboard layout from the option menu: despite calling emulator_init the keyboard doesn't behave properly after that. Quitting and restarting fixes.

In which situations does the issue arise ? Is it linked to a kind of keyboard (e.g USB, PS/2 ...) ? To a version of windows ? How is the layout configured in windows ? etc ...

**Comment by ColinPitrat** [comment]
The need to restart the emulator probably comes from the fact that input_init is not called ...

**Comment by ColinPitrat** [comment]
Note that a solution could be to support configuring keyboard mapping, allowing any key on the PC keyboard to be mapped to any CPC keys (including joystick, and potentially emulator shortcuts). This would cover issues #28 and #29 too and replace the kbd_layout variable. This would be saved to / loaded from a dedicated file. Default maps could be provided for the most common use cases.

**Comment by sebhz** [comment]
Nice idea. I second this. This would also be a nice answer to users with German/Italian/Japanese/any keyboard that is not UK/French/Spanish - which account for quite a number of people :-)

I will still do a couple more experiments on my side: I have access to a couple of MS Windows and Linux machines, laptops and desktops, with a variety of keyboards. As you suggested It would be good to understand a bit more the extent of the problem before moving to a solution. I won't be able to look at this before a few days though.

**Comment by sebhz** [comment]
I just spent a couple of hours coding a simple mapping extractor. See https://github.com/sebhz/sdl_keymap
I ran it on three different keyboards under Ubuntu (French, English US and English UK), results are in the repository. They seem pretty aligned with the Caprice32 mapping (I did not check every single lines though).
I still have to make this work under MS Windows (silly problems with console redirection) - maybe this will show something different.

**Comment by sebhz** [comment]
...and of course I just made a huge mistake in my repo and erased everything :-(

**Comment by ColinPitrat** [comment]
Argh, too bad I closed the tab containing it :-(
How did it happen ? The purpose of the git repo is to avoid it, I'd expect no easy command can nuke it !

**Comment by sebhz** [comment]
It's back online. Look at the two keymap_fr files. Pretty interesting. Ubuntu does what it is supposed to do. Under MS Windows, SDL does not seem to abide by the system keyboard mapping: of course when I did my trial on MS Windows, my system was set on a French locale, with a French keyboard, and all the keys were perfectly OK when typing in any application... yet it seems like SDL still thinks I am set with a US keyboard !

**Comment by sebhz** [comment]
Just so that you know - I am currently working on a kbd layout parser... ETA in a couple of days. Unless you want to handle it your way - which is fine with me ! Just tell me so that we do not duplicate work :-)

**Comment by ColinPitrat** [comment]
You mean a way to import / export keyboard mappings ?
This is fine by me. I'm not working on this currently.
This will need some GUI and configuration modifications also but you can send intermediary versions before it's complete with unit tests, flags or configuration options to test it.

A few (non-definitive) thoughts on that:
 - mappings should be in a dedicated file (not mixed with the config)
 - initially I thought we should aim to replace both keyboard and kbd_layout with a single option being the mapping file but thinking more about it this will not work: keyboard influences the char available in the ROM that are not the same depending on the keyboard (cf src/rom_mods.c and http://www.cpcwiki.eu/index.php/Keyboard_Versions#Character_Set_ROMs - e.g: French CPC has ù instead of | the latter not being available at all, you have to type `ùcpm` where an English CPC needs `|cpm`)
 - the files could be put in resources with a specific extension (e.g: .map)
 - we could start without a mapping editor but this would be a nice addition in the future, not sure of which form
 - Should we include CPC joysticks in the mapping (replacing or extending joy_layout / init_joystick_emulation in src/cap32.cpp ? I'm not sure of that ...) ? And Caprice keys (F1...) ?

**Comment by sebhz** [comment]
Yes.
> mappings should be in a dedicated file (not mixed with the config)
Agreed.
> initially I thought we should aim to replace both keyboard and ...
Yes. CPC.keyboard will still be needed. And CPC.kbd_layout would need to be the name of the resource file to use (with fallback to US/UK in case the file does not exist or is not defined).
> the files could be put in resources with a specific extension (e.g: .map)
Yes.
> we could start without a mapping editor but this would be a nice addition in the future, 
> not sure of which form
A full GUI editor seemed a bit hard to swallow for a first trial, so I put this as future work anyway.
> Should we include CPC joysticks in the mapping (replacing or extending joy_layout /
> init_joystick_emulation in src/cap32.cpp ? I'm not sure of that ...) ? And Caprice keys (F1...) ?
I think joysticks would be great. I left out caprice keys for now.

I also realized that this will have implications one the virtual keybard, as we would need to also redefine the "inverse keymap" from the configuration file...

**Comment by ColinPitrat** [comment]
> I also realized that this will have implications on the virtual keyboard, as we would need to also redefine the "inverse keymap" from the configuration file...

Good point. I guess we would need a char -> CPC_key map in the code and then generate the char -> SDL event from it using the keymap.

**Comment by sebhz** [comment]
The next "big thing" I was planning to look at was non-ASCII characters in the virtual keyboard.
The freetype methods support Unicode faces natively (of course !), and the font we use has all the glyphs. I did a quick trial and the "only" problem is that I am afraid that the whole GUI must be converted to use wstrings instead of strings, at least under MS windows, in order to pass a dang Unicode value to freetype :-(
This will be fairly easy, but very tedious, not to mention funny conversion between string and wstring when reading some parameters.

**Comment by ColinPitrat** [comment]
Are there many characters that are concerned ? There may be a simpler workaround ...

**Comment by sebhz** [comment]
Not really: é è à ù for french kbd, £ for uk, Ñ ñ and peseta sign for spanish. Except for peseta, all can be "naturally" encoded on 8 bits (their unicode and iso8859-1 number are the same and are below 255).


Sent from my Samsung device

-------- Original message --------

**Comment by ColinPitrat** [comment]
The original problem is fixed. Non-ASCII characters in virtual keyboard are not really a priority.
