### ISSUE TITLE
Buggy sound on windows 7

### ISSUE THREAD

**Issue by ColinPitrat** [ColinPitrat/caprice32#79]
Previously discussed in issue #11.

In Fruity Frank, the sound behaves strangely on my wife windows. The sound when eating a fruit is monotonic and doesn't stop until another sound (other than the music, usually the purple monster falling) occurs. The sound of the purple monster is also monotonic but does stop when it reaches the ground.

**Comment by sebhz** [comment]
Not reproduced with the latest build under Win8 on my side. You can listen to a sound capture at https://drive.google.com/open?id=0BzbzdrIRxC5lNXNIRTJCci1pa2s. The purple monster appears after 8 seconds.

**Comment by CodyMast** [comment]
There is no problem of sound under windows 10, creator update. It's perfect !

**Comment by ColinPitrat** [comment]
Closing as unreproducible.
