### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by kototama** [ColinPitrat/caprice32#81]
thank you so much! I spent the last days searching for a CPC emulator running on Linux or browser and none was satisfying. Too many dependencies (one required a LaTeX software that is 1 giga big, just to compile), or not working at all or even reimplementing a whole desktop in Java (JavaCPC).

You have few dependencies, and it just does what it should, with working sound and keyboard. Awesome!

I have some lags playing Arkanoid, not sure if it comes from the game or from the emulator. 

Anyway, thank you so much :)

**Comment by sebhz** [comment]
Hi !

It's good to see a satisfied user providing feedback :-)
Colin - who's the maintainer of this fork - seems to be taking a break these days, but I am sure he'll be delighted to read your comment when he is back online.

Feel free to open bug reports if you encounter any.

Regarding your lags with Arkanoid,  I am not seeing anything like this on my side (I am mostly playing with the MS Windows build these days, though).
However I do remember that the game was slowing down noticeably on my original CPC machine, as soon as there were many sprites on the screen. Are you seeing lags - like the display stuttering (e.g. frame drops) or just slow downs ? Is the frame rate dropping when you see those ? Frame rate should be displayed by default, if not you can show/remove it by pressing  F8.

**Comment by kototama** [comment]
FPS stay at ~50 so maybe it's just caused by the game in fact.

**Comment by ColinPitrat** [comment]
It's nice to get some positive feedback ! As said Seb, please do open issues if you encounter any problem (whether it's a bug, a missing feature, something unclear ...).

Keeping the dependencies minimal is the spirit. Especially considering most distributions do not provide a package and therefore users will have to build themselves, installing development package for each dependency.

I also remember the lags in Arkanoid on my real CPC. I confirm this is not an emulator issue but a problem with the original game.
