### ISSUE TITLE
Latest release process seems broken

### ISSUE THREAD

**Issue by sebhz** [ColinPitrat/caprice32#91]
The latest release dates from March 26th 2099 (!). Is this expected ?

**Comment by ColinPitrat** [comment]
It's a hack to ensure it's always the first one in the list of releases.
Unfortunately, releases are ordered by date of creation of the release name, not by date of last update ...

**Comment by sebhz** [comment]
OK - but still, the "latest" release tag points to 0d162f3, which is pretty old.
Wasn't it supposed to be regenerated each time a new successful build occurred ?

**Comment by ColinPitrat** [comment]
I'll check if there's a way to make the tag progress.

**Comment by ColinPitrat** [comment]
Thanks to a hugly hack, I improved the situation:
 - the 'latest' tag is now valid
 - the 'latest' release points to the right tag and commit 
However, I couldn't find a way to make the release date itself be updated.
I'll see next time I release a version whether this behaves well or not. Worse case, I'll have to delete the 'latest' release every time I do a major release (to preserve the order).
