### ISSUE TITLE
'x' key doing nothing when enabling joystick emulation

### ISSUE THREAD

**Issue by kototama** [ColinPitrat/caprice32#97]
I enabled joystick emulation and typing `Z` works. However typing `X` does not produce anything. Were there two types of fire/buttons in the original amstrad? is that a bug?

I am using `kbd_layout=1` (french) ; the keys are mapped correctly when typing.

**Comment by ColinPitrat** [comment]
I suspect you are using an old version under windows ?
In the latest release, kbd_layout is not a number anymore but a string. For example:
`kbd_layout=keymap_fr_linux.map`

The latest version can be downloaded here: https://github.com/ColinPitrat/caprice32/releases

**Comment by kototama** [comment]
I am using Linux and compiling the source. I pulled the latest version but now I have a compilation error:

```
obj/linux/src/gui/src/CapriceRomSlots.o: In function `wGui::CapriceRomSlots::CapriceRomSlots(wGui::CRect const&, wGui::CWindow*, wGui::CFontEngine*, std::string, int, wGui::CButton*)':
CapriceRomSlots.cpp:(.text+0x198): undefined reference to `listDirectory(std::string)'
obj/linux/src/gui/src/CapriceRomSlots.o: In function `wGui::CapriceRomSlots::getAvailableRoms()':
CapriceRomSlots.cpp:(.text+0x12c0): undefined reference to `listDirectory(std::string)'
collect2: error: ld returned 1 exit status
makefile:166: recipe for target 'cap32' failed
make: *** [cap32] Error 1
```

**Comment by ColinPitrat** [comment]
I was about to suggest it :-)
Is the joystick emulation issue fixed when using keymap_fr_linux or keymap_fr_win ?

**Comment by kototama** [comment]
Joystick is working but the 'x' key does not do anything. Maybe because of the game? How can I test that?

**Comment by ColinPitrat** [comment]
You can check before starting the game.
In the basic interface (where you type run"<game>"), if you press z, x, up, down, left or right with the joystick emulation enabled you will get different input than with it disabled. Fire buttons will display X and Z (instead of the lower case letter corresponding to the key) and up, down, left & right will display arrows.

**Comment by ColinPitrat** [comment]
For example here, I pressed azertywxcv followed by up, down, left, right:
![screenshot_20170630_125037](https://user-images.githubusercontent.com/1541863/27734445-c6a23cb8-5d92-11e7-85e9-6c7b93af190b.png)

**Comment by kototama** [comment]
Thank you for your detailed help. It works, I have a big 'Z' displayed. It just do no nothing in the games I tested (mission elevator and gauntlet). Hum. Thank you. I will try to find more information on the game.

Sorry that I confused that with a bug.

**Comment by ColinPitrat** [comment]
No problem. Do not hesitate to open other tickets if you encounter an issue.
